// export const plans = [
//   {
//     name: "Starter",
//     price: "₹2,999",
//     period: "/mo",
//     features: [
//       "Basic project tracking",
//       "AI budget estimation",
//       "Email support",
//       "Up to 3 projects",
//       "Community access",
//     ],
//     button: "Choose Starter",
//   },
//   {
//     name: "Prime",
//     price: "₹5,999",
//     period: "/mo",
//     features: [
//       "All Starter features",
//       "Advanced site verification",
//       "Priority email support",
//       "Up to 10 projects",
//       "Team collaboration",
//       "Custom reports",
//     ],
//     button: "Choose Prime",
//   },
//   {
//     name: "Professional",
//     price: "₹9,999",
//     period: "/mo",
//     features: [
//       "All Prime features",
//       "Unlimited projects",
//       "Phone & chat support",
//       "AI-powered analytics",
//       "Dedicated onboarding",
//       "Integration API",
//     ],
//     button: "Choose Professional",
//   },
//   {
//     name: "Enterprise Custom",
//     price: "Contact Us",
//     period: "",
//     features: [
//       "All Professional features",
//       "Custom integrations",
//       "Dedicated account manager",
//       "On-site training",
//       "24/7 priority support",
//       "Custom SLA",
//     ],
//     button: "Contact Sales",
//   },
// ];

import { Building, Crown, Shield, Sparkles } from "lucide-react";

export const plans = [
  {
    name: "Starter",
    price: "₹2,999",
    period: "/mo",
    description: "Perfect for clients, individual contractors, and small projects",
    color: "from-blue-400 to-blue-600",
    bgColor: "bg-gradient-to-br from-blue-50 to-blue-100",
    features: [
      "Basic project tracking",
      "AI budget estimation",
      "Email support",
      "Up to 3 projects",
      "Community access",
    ],
    buttonText: "Start with Starter",
    popular: false,
    icon: Building,
  },
  {
    name: "Prime",
    price: "₹5,999",
    period: "/mo",
    description: "Ideal for growing construction businesses",
    color: "from-purple-500 to-pink-500",
    bgColor: "bg-gradient-to-br from-purple-50 to-pink-50",
    features: [
      "All Starter features",
      "Advanced site verification",
      "Priority email support",
      "Up to 10 projects",
      "Team collaboration",
      "Custom reports",
    ],
    buttonText: "Choose Prime",
    popular: true,
    icon: Crown,
  },
  {
    name: "Professional",
    price: "₹9,999",
    period: "/mo",
    description: "Comprehensive solution for established companies",
    color: "from-emerald-500 to-teal-500",
    bgColor: "bg-gradient-to-br from-emerald-50 to-teal-50",
    features: [
      "All Prime features",
      "Unlimited projects",
      "Phone & chat support",
      "AI-powered analytics",
      "Dedicated onboarding",
      "Integration API",
    ],
    buttonText: "Go Professional",
    popular: false,
    icon: Sparkles,
  },
  {
    name: "Enterprise",
    price: "Custom",
    period: "",
    description: "Tailored solutions for large enterprises",
    color: "from-orange-500 to-red-500",
    bgColor: "bg-gradient-to-br from-orange-50 to-red-50",
    features: [
      "All Professional features",
      "Custom integrations",
      "Dedicated account manager",
      "On-site training",
      "24/7 priority support",
      "Custom SLA",
    ],
    buttonText: "Contact Sales",
    popular: false,
    icon: Shield,
  },
];
