export const constructionFirms = [
  {
    id: 1,
    companyName: "Elite Builders Co.",
    companyLogo:
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758449486/logo_2_xqkdrk.webp",
    specializations: ["Luxury Residential", "High-end Commercial"],
    verified: true,
    status: "Active",
    yearsInBusiness: 15,
    totalProjects: 139,
    city: "Mumbai",
    state: "Maharashtra",
    companyPhotos: [
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758439487/Building_2_xroatp.png",
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758439487/Building_1_edmfwz.png",
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758439823/Society_1_y4cr2h.png",
    ],
    services: [
      "Premium Construction",
      "Architecture",
      "Interior Design",
      "Project Management",
    ],
    rating: 4.9,
    reviewCount: 142,
  },
  {
    id: 2,
    companyName: "Modern Constructions",
    companyLogo:
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758449353/logo_1_klp6vl.jpg",
    specializations: ["Smart Homes", "Sustainable Construction"],
    verified: true,
    status: "Active",
    yearsInBusiness: 12,
    totalProjects: 97,
    city: "Bangalore",
    state: "Karnataka",
    companyPhotos: [
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758439487/House_1_k6pciy.png",
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758440055/Society_2_clek6d.png",
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758444764/house_4_gpregv.png",
    ],
    services: [
      "Smart Construction",
      "Green Building",
      "Home Automation",
      "Energy Solutions",
    ],
    rating: 4.8,
    reviewCount: 89,
  },
  {
    id: 3,
    companyName: "Green Build Solutions",
    companyLogo:
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758449353/logo_3_x3ulrk.png",
    specializations: ["Commercial Towers", "Mixed-use Development"],
    verified: true,
    status: "Inactive",
    yearsInBusiness: 20,
    totalProjects: 241,
    city: "New Delhi",
    state: "Delhi",
    companyPhotos: [
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758445733/tower_1_qfiaxk.png",
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758445215/tower_2_hbdhb9.png",
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758445870/tower_3_owuu2l.png",
    ],
    services: [
      "Commercial Construction",
      "Urban Planning",
      "Infrastructure",
      "Real Estate",
    ],
    rating: 4.7,
    reviewCount: 63,
  },
  {
    id: 4,
    companyName: "Urban Developers",
    companyLogo:
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758449575/logo_4_y8hkdu.avif",
    specializations: ["Waterfront Properties", "Resort Development"],
    verified: false,
    status: "Active",
    yearsInBusiness: 7,
    totalProjects: 53,
    city: "Goa",
    state: "Goa",
    companyPhotos: [
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758446771/resort_3_z1z5vf.png",
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758445623/resort_1_yfed0r.png",
      "https://res.cloudinary.com/dnzbzvfxn/image/upload/v1758446113/resort_2_ckd8xw.png",
    ],
    services: [
      "Coastal Construction",
      "Resort Development",
      "Marine Engineering",
      "Hospitality",
    ],
    rating: 4.8,
    reviewCount: 97,
  },
];
