export const projects = [
  {
    id: "1",
    name: "Skyline Residency Towers",
    status: "In Progress",
    type: "Residential",
    location: "Mumbai, Maharashtra",
    timeline: "18 months",
    budget: "25L",
    budgetUsed: "16L",
    progress: 65,
    description:
      "A modern 25-story residential tower with premium amenities including a rooftop garden, fitness center, and underground parking.",
    startDate: "2024-01-11",
    expectedEndDate: "2025-07-15",
    workers: 45,
    engineers: 8,
    photos: [
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
      "https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg",
      "https://images.pexels.com/photos/1170412/pexels-photo-1170412.jpeg",
    ],
    manager: "Rajesh Kumar",
    client: "Shivam Builders Pvt. Ltd.",
  },
  {
    id: "2",
    name: "Metro Mall Nashik",
    status: "Completed",
    type: "Commercial",
    location: "Nashik, Maharashtra",
    timeline: "24 months",
    budget: "38L",
    budgetUsed: "38L",
    progress: 100,
    description:
      "A state-of-the-art shopping center featuring 150 retail stores, food court, and entertainment facilities spread across 500,000 sq ft.",
    startDate: "2022-03-17",
    expectedEndDate: "2024-03-10",
    workers: 120,
    engineers: 15,
    photos: [
      "https://images.pexels.com/photos/2219024/pexels-photo-2219024.jpeg",
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
      "https://images.pexels.com/photos/2747449/pexels-photo-2747449.jpeg",
    ],
    manager: "Priya Deshmukh",
    client: "Metro Developers Group",
  },
  {
    id: "3",
    name: "Thane River Bridge Project",
    status: "In Progress",
    type: "Infrastructure",
    location: "Thane, Maharashtra",
    timeline: "36 months",
    budget: "50L",
    budgetUsed: "18L",
    progress: 35,
    description:
      "Construction of a new suspension bridge connecting two major districts, featuring pedestrian walkways and bike lanes.",
    startDate: "2023-08-05",
    expectedEndDate: "2026-08-20",
    workers: 85,
    engineers: 22,
    photos: [
      "https://images.pexels.com/photos/327882/pexels-photo-327882.jpeg",
      "https://images.pexels.com/photos/161154/pexels-photo-161154.jpeg",
      "https://images.pexels.com/photos/1209610/pexels-photo-1209610.jpeg",
    ],
    manager: "Amit Patil",
    client: "Maharashtra Infrastructure Corp",
  },
  {
    id: "4",
    name: "Green Valley Homes",
    status: "On Hold",
    type: "Residential",
    location: "Andheri, Maharashtra",
    timeline: "14 months",
    budget: "30L",
    budgetUsed: "6L",
    progress: 20,
    description:
      "Eco-friendly residential community with 50 energy-efficient homes featuring solar panels and sustainable materials.",
    startDate: "2024-02-09",
    expectedEndDate: "2025-04-01",
    workers: 30,
    engineers: 6,
    photos: [
      "https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg",
      "https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg",
      "https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg",
    ],
    manager: "Sneha Mehta",
    client: "EcoLife Realty",
  },
  {
    id: "5",
    name: "Pune Corporate Tower",
    status: "In Progress",
    type: "Commercial",
    location: "Pune, Maharashtra",
    timeline: "30 months",
    budget: "45L",
    budgetUsed: "36L",
    progress: 80,
    description:
      "40-story corporate office tower with modern glass facade, smart building technology, and premium office spaces.",
    startDate: "2022-11-27",
    expectedEndDate: "2025-05-05",
    workers: 95,
    engineers: 18,
    photos: [
      "https://images.pexels.com/photos/2047905/pexels-photo-2047905.jpeg",
      "https://images.pexels.com/photos/1647962/pexels-photo-1647962.jpeg",
      "https://images.pexels.com/photos/834892/pexels-photo-834892.jpeg",
    ],
    manager: "Vikram Joshi",
    client: "Infospace Developers",
  },
  {
    id: "6",
    name: "Mumbai-Pune Expressway Expansion",
    status: "Completed",
    type: "Infrastructure",
    location: "Lonavala, Maharashtra",
    timeline: "18 months",
    budget: "33L",
    budgetUsed: "33L",
    progress: 100,
    description:
      "Major highway expansion adding two lanes in each direction with new overpasses and improved drainage systems.",
    startDate: "2022-06-11",
    expectedEndDate: "2023-12-15",
    workers: 150,
    engineers: 25,
    photos: [
      "https://images.pexels.com/photos/2886937/pexels-photo-2886937.jpeg",
      "https://images.pexels.com/photos/1051838/pexels-photo-1051838.jpeg",
      "https://images.pexels.com/photos/2740956/pexels-photo-2740956.jpeg",
    ],
    manager: "Anjali Nair",
    client: "MSRDC (Maharashtra State Road Development Corporation)",
  },
  {
    id: "7",
    name: "Juhu Beach Resort & Spa",
    status: "In Progress",
    type: "Commercial",
    location: "Juhu Beach, Maharashtra",
    timeline: "42 months",
    budget: "40L",
    budgetUsed: "18L",
    progress: 45,
    description:
      "Premium resort complex with 200 rooms, spa facilities, conference centers, and beachfront amenities.",
    startDate: "2023-04-01",
    expectedEndDate: "2026-10-10",
    workers: 180,
    engineers: 28,
    photos: [
      "https://images.pexels.com/photos/1134176/pexels-photo-1134176.jpeg",
      "https://images.pexels.com/photos/261156/pexels-photo-261156.jpeg",
      "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg",
    ],
    manager: "Karan Malhotra",
    client: "Coastal Resorts India Ltd.",
  },
  {
    id: "8",
    name: "Navi Mumbai Housing Project",
    status: "On Hold",
    type: "Residential",
    location: "Navi Mumbai, Maharashtra",
    timeline: "15 months",
    budget: "35L",
    budgetUsed: "3.5L",
    progress: 10,
    description:
      "Family-friendly housing development with 75 single-family homes, community center, and playgrounds.",
    startDate: "2024-05-16",
    expectedEndDate: "2025-08-01",
    workers: 40,
    engineers: 7,
    photos: [
      "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg",
      "https://images.pexels.com/photos/280229/pexels-photo-280229.jpeg",
      "https://images.pexels.com/photos/1396569/pexels-photo-1396569.jpeg",
    ],
    manager: "Neha Sharma",
    client: "Ghar Aangan Developers",
  },
];
